### ISSUE TITLE
Set movement limit

### ISSUE THREAD

**Issue by rafaelcmrj** [dixonandmoe/rellax#114]
Is there any way I can limit the parallax to not go over the initial position? (stop when the element reaches its initial position)

**Comment by spncrmoo** [comment]
Did you ever get to the bottom of this?

**Comment by rafaelcmrj** [comment]
@spncrmoo what do you mean? still having the same problem

**Comment by moeamaya** [comment]
No unfortunately that's out of the scope of this library. We've tested quite a few different ways to try and only animate the element when it's in the browser viewport, but nothing has worked reliably cross browser.

**Comment by rafaelcmrj** [comment]
@moeamaya it's not related to the browser viewport... imagine you have an object in the initial position at 30px on Y coordinate.. when parallax start to happen, the object wil go to Y 80px and then start coming back to its original position.. 70px, 60px, 50px and so on... I'd like to stop the parallax when it reaches its original position (30px).

**Comment by p-realinho** [comment]
@rafaelcmrj It's not possible at the moment.
But (in theory) it shouldn't be too hard to implement.

- We'd need an option to enable the feature ofc.
- Possibly force those elements to use the `center` option (since they can't start parallaxing from their original positions).
- When calculating the transform, check if the option is enabled.
- If so, depending on the element's speed we know whether to "block" positive or negative transform values.
If I'm not mistaken, when, on an element with a positive speed, the transform calculation returns a negative value, we should return `0` instead (And do the opposite for negative speed values. So negative speed, allow only negative transforms).

That should do it. Any volunteer? 😅 
Although, I must say, without any sort of easing function, I doubt it'll look tooo great. But I could be wrong.

**Comment by Probablybest** [comment]
@p-realinho Did limiting the amount of pixels to a max number, on a parallax element, ever get implemented into this?

**Comment by p-realinho** [comment]
@Probablybest Not that I know of.
I'll see if I can get the time to look into it in the next few days.

**Comment by Probablybest** [comment]
@Probablybest that would be brilliant if you could take a look. Ideally it would be great if you can set the top and bottom max movement position with some kind of data attr.

**Comment by p-realinho** [comment]
Yea, I was just thinking that would probably make more sense.
Something like a range.
So you could specify stuff like `<10px`, `-10px .. 30px`, `>0px`.
But I gotta take a look at the code and see if it's doable.

**Comment by p-realinho** [comment]
Hey @Probablybest. Just added a PR for this.
I also just noticed, before submitting it, that there is a very similar PR already waiting for merge, so I'm not sure what'll happen next.

Anyways, I went for a `data-rellax-range`, where we could pass an expression to limit the position values, but, although it was much more flexible, I was having trouble persisting the correct positions of the elements once they went past the limit defined.

So I ended up with `data-rellax-min` and `data-rellax-max`.

I gave an example on the PR on how to solve this specific issue and added a file to the tests folder with some examples (range.html).

**Comment by Probablybest** [comment]
Looks brilliant! Exactly what I needed. Thanks for doing that so quickly too.

**Comment by Probablybest** [comment]
@p-realinho I've integrated this into my site and the data-rellax-max is working nicely. But the data-rellax-min won't change from `transform: translate3d(0px, 0px, 0px);`. I'm using `<div class="rellax" data-rellax-speed="-5" data-rellax-min="-120" data-rellax-max="120">min: -120 | max: 120</div>` within the `body`.

**Comment by guyaldous1** [comment]
Hi there,

I just stumbled across this, I was wondering if there was a way to set a default for this with JS instead of calling it inline as a data attribute every time I want to use it?
