### ISSUE TITLE
No iOS Safari support

### ISSUE THREAD

**Issue by blairwigley** [dixonandmoe/rellax#14]
Looks like the plugin doesn't work with Safari on iOS (tried iOS 8,9 & 10)  - works fine with OSX Safari.

**Comment by p-realinho** [comment]
Hi. The plugin is, by default, disabled on mobile. 

"Rellax limits the parallax feature to laptop/desktop screens since the effect is negligible on smaller screens."

**Comment by blairwigley** [comment]
Ah that's a pity, the feature would be quite useful for iPads etc.

**Comment by blairwigley** [comment]
All good - realised I can just comment out line 32 - thanks for your help.

**Comment by moeamaya** [comment]
Hey @blairwigley. Thanks for bringing this up, but one of the major reasons we wrote this is to have a stable parallax implementation that is maintained. The primary reason so many parallax repos are abandon-ware is because of all the issues that mobile/tablet's can cause. 

Until device manufacturers and browsers generalize how to handle transform, scroll, touch, then the main rellax codebase will avoid working on those devices.
