### ISSUE TITLE
Mobile performance 

### ISSUE THREAD

**Issue by vilav** [dixonandmoe/rellax#15]
Hi

Thanks for making this available. Love the desktop experience. Very smooth. But the mobile experience is not performant and doesn't seem to implement parallax at all. Any tips to improve that? (iOS 10 > Latest Chrome  + Safari)

Thanks

**Comment by moeamaya** [comment]
Hey @vilav, thanks for checking out Rellax. One of the major reasons we wrote this is to have a stable parallax implementation that is maintained. The primary reason so many parallax repos are abandon-ware is because of all the issues that mobile/tablet's can cause.

Until device manufacturers and browsers generalize how to handle transform, scroll, touch, then the main rellax codebase will avoid working on those devices for now.

**Comment by vilav** [comment]
Hi @moeamaya, true it's quite an uphill task. Is there a way to entirely disable rellax on mobile though so it works on desktop-only? Right now, the normal scroll seems interrupted and jerky for some reason. Any tips on how to improve that! Thanks again. Cheers

**Comment by moeamaya** [comment]
Which device/OS are you on? The code right now tests for device orientation capability to disable the feature, but if your device doesn't have that it will run.

**Comment by vilav** [comment]
On the latest iOS, on both Chrome & Safari latest versions. If an element that has parallax (on Desktop) is in the viewport on mobile, it feels like the scroll get dragged like it has some jank.

![file sep 21 1 50 47 pm](https://cloud.githubusercontent.com/assets/849098/18699233/8102f526-8002-11e6-9fe7-2c51f2f93b41.png)

**Comment by moeamaya** [comment]
This is a layout / CSS issue which has been on my TODO list since launch lol. I'll shoot for one of these weekends in the next 4 weeks to get this fixed up so as not to confuse folks!
