### ISSUE TITLE
iOS - iPhone

### ISSUE THREAD

**Issue by bogdanfer** [dixonandmoe/rellax#17]
does this work for you on iOS (iPhone) - Safari? 
thanks!

**Comment by moeamaya** [comment]
Hey @bogdanfer. Thanks for bringing this up, but one of the major reasons we wrote this is to have a stable parallax implementation that is maintained. The primary reason so many parallax repos are abandon-ware is because of all the issues that mobile/tablet's can cause.

Until device manufacturers and browsers generalize how to handle transform, scroll, touch, then the main rellax codebase will avoid working on those devices.
