### ISSUE TITLE
Issue with npm

### ISSUE THREAD

**Issue by nathanaelphilip** [dixonandmoe/rellax#3]
I’m getting an `Uncaught Reference Error: Rellax is not defined` error.

here’s how I’m calling it:

```
require('rellax');
let rellax = new Rellax('.rellax');
```

**Comment by moeamaya** [comment]
@nathanaelphilip The library exposes `Rellax` as a global variable. Gross, I know, but the intention with the code is to be small as possible for use on simple static websites.

**Comment by nathanaelphilip** [comment]
I’m still sort of a JS newb, so could you show me an example? :)

**Comment by moeamaya** [comment]
Sure. Since it's global there's no option to `require('rellax')`, which means you have to point to where it's at in your files. For instance on your homepage at the bottom of the `<body>` but before your js code put `<script src=node_modules/relllax/rellax.min.js></script>` or where ever node_modules is at in your file structure

**Comment by nathanaelphilip** [comment]
ahhhh ok, so using npm is almost pointless right now. thanks!

**Comment by moeamaya** [comment]
Yup, pretty much :) Closing now
