### ISSUE TITLE
page hard refresh

### ISSUE THREAD

**Issue by wupadach** [dixonandmoe/rellax#52]
Browser: firefox
when page is refreshed with CTRL+F5 or CTRL+SHIFT+R

element that has parallax effect changes position

example here: [http://www.iambailon.com/](http://www.iambailon.com/)

same thing happens with my page
![default](https://cloud.githubusercontent.com/assets/11226933/24910858/29b24e58-1eda-11e7-88c7-d97e98be1524.PNG)
![2](https://cloud.githubusercontent.com/assets/11226933/24910857/29a79b70-1eda-11e7-9694-94a4ad099c57.PNG)

**Comment by p-realinho** [comment]
I haven't done much testing, but as far as I can tell, it could be due to the images not being fully loaded yet when Rellax tries to do its calculations.
Could you try to create the Rellax instance inside of window.onload and see if that solves it?
Something like
```
window.onload = function(){
    var rellax = new Rellax('.rellax', {opt: val});
}
```
Then again, no testing was done, so I could be entirely wrong lol

**Comment by c0mrx** [comment]
@p-realinho Thanks! This worked wonders.

**Comment by rogeralbinoi** [comment]
Thanks! <3
