### ISSUE TITLE
stop translating when element is out of view

### ISSUE THREAD

**Issue by jackiboy** [dixonandmoe/rellax#6]
Hi.
Would it be possible to stop the element from translating when it moves out of view?
at the moment elements out of view are still translating as you scroll down your page.

Cheers,
Jack

**Comment by moeamaya** [comment]
Hey @jackiboy thanks for the issue. 

We had a `//TODO` in the code to address this but removed it since it didn't seem necessary. The primary issue we struggled with is locating DOM elements when they are translated via `translate3d()`. We're not opposed to a solid implementation that handles pre-fetching positions for elements that move faster than scroll or post-fetching for elements that move slower.

It's a great issue, but a complicated one, but happy to work with someone on implementing a reasonable solution.

**Comment by moeamaya** [comment]
Hey @jackiboy, going to close this for the moment unless there's performance issues on your end.
