### ISSUE TITLE
Is it possible to mix parallax animation with a css hover state animation?

### ISSUE THREAD

**Issue by thedonquixotic** [dixonandmoe/rellax#89]
I've got an image button that shifts the image to the up a little when you hover over it. 

I also want to have parallax effect on it. Is it possible at all to mix these?

I don't think I've ever seen two animations mixed in this way so I assume it's not but I've also never seen explicitly not to be, and I've never heard an explanation of why it wouldn't.

**Comment by thedonquixotic** [comment]
Oh hey, sweet I got it to work! I just applied the rellax to a container of the image. Woo!

**Comment by p-realinho** [comment]
Hi, glad you got it working.

The reason why it's "not" possible* is because Rellax does its thing by changing the `style=""` property of the element(s) it's applied to, and uses the `transform` property for the animations.
*(given that you're also using `transforms` for the animation and, styling the rellax element's `:hover`)

Two possible solutions are:
- (the one you went for) applying Rellax and the hover styles to different elements, or
- using a different property, other than `transform`, for the `:hover` animation/transition (IE. `top/bottom`, `margin`, etc)

The problem is, the properties inside `style=""` have a higher [CSS Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) (the highest, I think), which means these properties' values will override all the other values of the same property.

(Sorry if that was a bit confusing... I'm not a native English speaker. 😅
A quick [search about CSS Specificity](https://www.google.com/search?q=CSS+Specificity) should get you there.)

Hope it helps. 🙂

**Comment by thedonquixotic** [comment]
Yes, thank you! I had read that CSS specificity was higher for inline styles but I didn't know if that was overridden by a new event or something like hover. But hover is treated more like a state than an event I guess. 

Thanks!

**Comment by p-realinho** [comment]
Yup.
To sum it up, it has the same specificity as "Class selectors (e.g., `.example`), attributes selectors (e.g., `[type="radio"]`) and pseudo-classes (e.g., `:hover`)".
So it could be overridden by ID selectors, and will always be overridden by inline styles.
