### ISSUE TITLE
Parallax effect isn't working

### ISSUE THREAD

**Issue by Techassi** [dixonandmoe/rellax#98]
Hi,

I recently did find Rellax and wanted to use it on my website.
I did the following:
1. Link the script at the bottom of my page like this: `<script src="js/rellax.js"></script>` Yes I don't use the minified version for the development process.
2. I added the `.rellax` class to all my desired elements
3. I added this code at the bottom of may page aswell: `<script> var rellax = new Rellax();</script>`
4. I refreshed the page to see the result, but none of the elements are moving. The style get's added but stays at `transform: translate3d(0px, 0px, 0px);` even when scrolling.

I am using the latest version of your script and Chrome version 63.0.3239.132.

So I hope you can help me fixing this problem or maybe I dicovered a bug.

**Comment by p-realinho** [comment]
Hi! Thanks for using Rellax.

Could you check if:
1. **You're using it on `inline` elements.** (Inline elements can't be `transform`ed) (Not likely the case, since you mention the `translate` remains at `0px`... but, just to be sure).
    - Possible solution: Make them `display: block`, or `inline-block`, or any other than `inline`.
2. And if **you're not scrolling the `html`/the `document`, but a child element instead.** (As of right now, Rellax only works with the "main" scrollbar, since it makes use of `window.pageYOffset`).

Hope it helps.

**Comment by Techassi** [comment]
Hi! Thanks for your quick response.

So I checked the following:
1. My elements displayed aren't `inline`. They are all `block`.
2. I am scrolling my whole `document`. I am hiding the vertical `scrollbar` but changing this didn't make a difference. I looked at your code and I am aware you are using `pageYOffset` so I already made sure my document is scrolling.

So my guess is the `transform` doesn't get updated for whatever reason. I can provide further information (`DOM, JavaScript`) if needed.

I hope to hear back soon!

**Comment by Techassi** [comment]
Ok....
I did find the solution: Apparently `overflow-x: hidden` is repsonsible for the script not working. Seems like I didn't refreshed the page properly in the first place. 

I think it's a bit odd the script doesn't work if you hide `overflow-x`. I don't know if thats something `JavaScript `(in general) related or something about the script itself or some weird `CSS `bug.

I hope you can explain why the script didn't work with `overflow-x: hidden` used on body.

I'll mark the issue as closed and hope to hear back soon.

**Comment by Techassi** [comment]
So I did a little more experimenting:
- Applying `overflow `attribute to body will cause Rellax not to work. Even `inherit`, `auto `or `scroll `will break it.
- Dynamically setting overflow via `JavaScript `doesn't work either. For my usecase I have to do some trickery (adding additional HTML syntax to make my effect work all across my website).

So my best guess is this is apparently a bug either in `Rellax`, `JavaScript `or `CSS`.

**Comment by canzian** [comment]
Hi!
I've faced this bug too.
The problem is here: https://github.com/dixonandmoe/rellax/blob/master/rellax.js#L193
The `window.pageYOffset` isn't `undefined`, but it always returns 0 if `overflow` attribute is on the `body`.
I just inverted the condition for this:
`posY = (document.body || document.documentElement || document.body.parentNode).scrollTop || window.pageYOffset;`. Apparently its working correctly in Safari, Chrome, Firefox.  
BTW, I've made a pull request with this fix.

**Comment by moeamaya** [comment]
Closed with canzian's pull request

**Comment by razichaudhary** [comment]
rellax js not working

**Comment by MitichPavel** [comment]
Hi,
rellax.min.js don't working in chrome 86.0.4240.198 on huawei p20 pro, maybe do you help me understand why?
ellements whitch must be "parallax" are not visible on website.
